apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-mock-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-mock-project
  template:
    metadata:
      labels:
        app: jenkins-mock-project
    spec:
      containers:
        - name: jenkins-mock-project
          image: gutardivo/jenkins-mock-project:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-mock-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins-mock-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
